### ISSUE TITLE
Background image does not show up

### ISSUE THREAD

**Issue by serhiicss** [serhiicss/owls-build-to-learn#1]
Header image doesn't work for some reason. ../img/header-bg.jpg

**Comment by justirma** [comment]
@serhiicss It's looking in the wrong location for the img. 

Currently you're using `url(../img/header-bg.jpg)` Here it's moving up a directory and trying to find the img folder. 

Since the CSS and img folders are on the same level, you don't have to move up a directory to reach the img folder. Try removing the "../" ---> `url(img/header-bg.jpg)` that will work.

**Comment by serhiicss** [comment]
I did that and it still doesn't work... :(

**Comment by serhiicss** [comment]
Fixed. Thanks!
